#!/usr/bin/env python3
"""
AndroidGuides.com — Crawlable-HTML generator (P2)

Reads devices.json and writes devices-static.html: one plain-English,
plain-HTML sentence per device. This fragment is what AI crawlers and
non-JavaScript visitors read on /devices (they don't run the JS table,
so without this they'd see an empty page). Runs monthly in the same
GitHub Actions workflow as update_devices.py; the fragment is embedded
in the /devices WordPress page (auto-push arrives with P3).

Usage: python generate_static.py
"""

import json
from datetime import date, datetime
from pathlib import Path

from support_status import support_sentence, support_state

INPUT = Path(__file__).parent / "devices.json"
OUTPUT = Path(__file__).parent / "devices-static.html"

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]


def human(iso: str) -> str:
    d = datetime.fromisoformat(iso).date()
    return f"{MONTHS[d.month - 1]} {d.day}, {d.year}"


def esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "&#39;"))


def is_ended(eol: date, as_of: date) -> bool:
    """The EOL date is the final supported calendar day."""
    return eol < as_of


def sentence(d: dict, today: date) -> str:
    plain_name = f"{d['brand']} {d['model']}"
    clause = esc(support_sentence(d, today))
    device_link = f'<a href="/device/{esc(d["id"])}/">{esc(plain_name)}</a>'
    clause = clause.replace(esc(plain_name), f"<b>{device_link}</b>", 1)
    qualifier = (
        (d.get("support_window") or {}).get("provenance") or {}
    ).get("list_qualifier")
    qualifier_html = (
        f' <span class="source-scope">{esc(qualifier)}</span>' if qualifier else ""
    )
    return f"<li>{clause}{qualifier_html} (Released {human(d['released'])}.)</li>"


def main() -> int:
    data = json.loads(INPUT.read_text())
    devices = sorted(data["devices"], key=lambda x: x["released"], reverse=True)
    today = date.today()

    n = len(devices)
    brands = {}
    counts = {
        "supported": 0,
        "ending": 0,
        "guarantee_elapsed": 0,
        "ended": 0,
    }
    for d in devices:
        brands[d["brand"]] = brands.get(d["brand"], 0) + 1
        counts[support_state(d, today)] += 1
    brand_txt = ", ".join(f"{v} {k}" for k, v in sorted(brands.items()))

    items = "\n".join(sentence(d, today) for d in devices)
    html = f"""<!-- devices-static fragment · generated {data['generated']} · {n} devices · auto-generated by generate_static.py — do not hand-edit -->
<section id="agd-static">
  <h2>Android security update end dates — full list</h2>
  <p>As of {human(data['generated'])}, AndroidGuides.com tracks {n} Android devices ({brand_txt}):
  {counts['supported']} have a stated support window beyond 12 months, {counts['ending']} have a stated support window ending within 12 months,
  {counts['guarantee_elapsed']} have passed their stated guarantee period without a confirmed stop, and {counts['ended']} are confirmed no longer supported.
  Data refreshes monthly from manufacturer commitments and endoflife.date.</p>
  <details>
  <summary>Show all {n} devices as a plain text list</summary>
  <ul>
{items}
  </ul>
  </details>
</section>
"""
    OUTPUT.write_text(html, encoding="utf-8")
    print(
        f"[OK] wrote {OUTPUT} ({n} sentences; "
        f"{counts['supported']} supported / {counts['ending']} ending / "
        f"{counts['guarantee_elapsed']} guarantee elapsed / {counts['ended']} ended)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
